SET gp_autostats_mode = 'NONE';

INSERT INTO customer_address SELECT * FROM customer_address_ext;
INSERT INTO customer_demographics SELECT * FROM customer_demographics_ext;
INSERT INTO date_dim SELECT * FROM date_dim_ext;
INSERT INTO warehouse SELECT * FROM warehouse_ext;
INSERT INTO ship_mode SELECT * FROM ship_mode_ext;
INSERT INTO time_dim SELECT * FROM time_dim_ext;
INSERT INTO reason SELECT * FROM reason_ext;
INSERT INTO income_band SELECT * FROM income_band_ext;
INSERT INTO item SELECT * FROM item_ext;
INSERT INTO store SELECT * FROM store_ext;
INSERT INTO call_center SELECT * FROM call_center_ext;
INSERT INTO customer SELECT * FROM customer_ext;
INSERT INTO web_site SELECT * FROM web_site_ext;
INSERT INTO store_returns SELECT * FROM store_returns_ext;
INSERT INTO household_demographics SELECT * FROM household_demographics_ext;
INSERT INTO web_page SELECT * FROM web_page_ext;
INSERT INTO promotion SELECT * FROM promotion_ext;
INSERT INTO catalog_page SELECT * FROM catalog_page_ext;
INSERT INTO inventory SELECT * FROM inventory_ext;
INSERT INTO catalog_returns SELECT * FROM catalog_returns_ext;
INSERT INTO web_returns SELECT * FROM web_returns_ext;
INSERT INTO web_sales SELECT * FROM web_sales_ext;
INSERT INTO catalog_sales SELECT * FROM catalog_sales_ext;
INSERT INTO store_sales SELECT * FROM store_sales_ext;

DROP EXTERNAL TABLE IF EXISTS customer_address_ext;
DROP EXTERNAL TABLE IF EXISTS customer_demographics_ext;
DROP EXTERNAL TABLE IF EXISTS date_dim_ext;
DROP EXTERNAL TABLE IF EXISTS warehouse_ext;
DROP EXTERNAL TABLE IF EXISTS ship_mode_ext;
DROP EXTERNAL TABLE IF EXISTS time_dim_ext;
DROP EXTERNAL TABLE IF EXISTS reason_ext;
DROP EXTERNAL TABLE IF EXISTS income_band_ext;
DROP EXTERNAL TABLE IF EXISTS item_ext;
DROP EXTERNAL TABLE IF EXISTS store_ext;
DROP EXTERNAL TABLE IF EXISTS call_center_ext;
DROP EXTERNAL TABLE IF EXISTS customer_ext;
DROP EXTERNAL TABLE IF EXISTS web_site_ext;
DROP EXTERNAL TABLE IF EXISTS store_returns_ext;
DROP EXTERNAL TABLE IF EXISTS household_demographics_ext;
DROP EXTERNAL TABLE IF EXISTS web_page_ext;
DROP EXTERNAL TABLE IF EXISTS promotion_ext;
DROP EXTERNAL TABLE IF EXISTS catalog_page_ext;
DROP EXTERNAL TABLE IF EXISTS inventory_ext;
DROP EXTERNAL TABLE IF EXISTS catalog_returns_ext;
DROP EXTERNAL TABLE IF EXISTS web_returns_ext;
DROP EXTERNAL TABLE IF EXISTS web_sales_ext;
DROP EXTERNAL TABLE IF EXISTS catalog_sales_ext;
DROP EXTERNAL TABLE IF EXISTS store_sales_ext;

ANALYZE;
